defmodule ShopWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :shop

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_shop_key",
    signing_salt: "TevsdL/H",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :shop,
    gzip: not code_reloading?,
    only: ShopWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :shop
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  # So this is a plug on a function the : indicates the function and after , is the opts
  # Allways remember that is the plug implicates before the router or session or other plugs need to be above it
  # Because plugs are executed in order
  plug :check_promo_code, "Hello there!"
  plug ShopWeb.Router


  # This is a plug function that checks for a promo code in the params
  # If the promo code matches "secret-code", it assigns :promo to true in the conn
  # Otherwise, it assigns :promo to false
  def check_promo_code(%Plug.Conn{:params => %{"promo" => promo_code}} = conn, opts) when promo_code == "secret-code" do
    # Only for debugging purposes
    IO.inspect(opts)
    # Assign :promo to true in the conn on phoenix 1.8 you need to use Plug.Conn.assign/3
    conn |> Plug.Conn.assign(:promo, true)
  end

  # This clause handles the case where the promo code does not match or is absent
  def check_promo_code(%Plug.Conn{} = conn, opts) do
    IO.inspect(opts)
    conn |> Plug.Conn.assign(:promo, false)
  end
end
